//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""90702192-24e2-476a-82dc-b16d6ea06ef6"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""8c525ee0-524a-4836-9437-49111582c36a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""a357fdef-1b7e-4341-8b5a-18c1486ee4a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""d7f2e1bf-f429-4306-a30d-53d92f9885aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""43699282-2b03-4eee-867b-df6aeb7de518"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mode0"",
                    ""type"": ""Button"",
                    ""id"": ""820ee45a-2d9e-4d59-b7ea-99393a77c746"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mode1"",
                    ""type"": ""Button"",
                    ""id"": ""4378fd93-1530-44ee-be82-06aa364eee75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mode2"",
                    ""type"": ""Button"",
                    ""id"": ""793e783d-8aaf-410e-8f43-c25faf0e47e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mode3"",
                    ""type"": ""Button"",
                    ""id"": ""bb9a8c1a-8935-439a-ad03-0fc6dcddd317"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eliminate"",
                    ""type"": ""Button"",
                    ""id"": ""abb76662-9c65-4d8a-8a82-7f1261d3efcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""13ac3302-2464-4562-ad2d-74a9c26a1059"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Translate"",
                    ""type"": ""Button"",
                    ""id"": ""d78061ea-74fb-4ff3-9815-7b648b98647b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Directions"",
                    ""type"": ""Value"",
                    ""id"": ""a3ae7cf1-7a01-4073-9d9f-ed6503fa56cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""90fe69e9-293a-4331-8fc0-351aa1702242"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8e2c534-2c06-4104-9f71-85e9aca59876"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5229d61-b9aa-4094-9aaa-97243394367b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ca01cbf-bbc7-4131-a2ab-3cb19e566c96"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38988370-0bbc-463f-9120-a150ca4949d3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c800ab42-ce72-4517-9d06-a498823e2a3f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e48088c4-0ac4-46d0-8580-cb4d33764394"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1880b1e4-f6a5-457f-a3e6-9fc59c5dda0e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba347bab-fbfe-44b7-8f28-daae6509fcc9"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38a8cfdd-6382-4046-88f9-28d77d7dcb66"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee05bd4-8fbf-47ea-b9af-3fefa89b64a0"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11fbff16-e79d-4cf1-a9cf-910d2631adfe"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b28a0c21-4741-459b-a08e-c2a3bae3e26c"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2232db2c-2710-4914-9237-2636a2c578b2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eliminate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""703c59cc-029f-49e0-95f0-aa19f165b2d1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9e16226-68b4-44c6-b90b-a7999a3bbf3b"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""123c61be-3ff1-4087-8a9d-cd3cf7498425"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b8c61a13-4a1d-4bfd-b865-4d01c0d80da1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""36f4d3b0-4f30-432a-9367-e5ddd00328eb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f07b02cf-c3be-4e15-8f3e-303c175a2de8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""96c2065b-f4ff-4ed4-93e6-c62bad5a4e47"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Back = m_UI.FindAction("Back", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_Confirm = m_UI.FindAction("Confirm", throwIfNotFound: true);
        m_UI_Space = m_UI.FindAction("Space", throwIfNotFound: true);
        m_UI_Mode0 = m_UI.FindAction("Mode0", throwIfNotFound: true);
        m_UI_Mode1 = m_UI.FindAction("Mode1", throwIfNotFound: true);
        m_UI_Mode2 = m_UI.FindAction("Mode2", throwIfNotFound: true);
        m_UI_Mode3 = m_UI.FindAction("Mode3", throwIfNotFound: true);
        m_UI_Eliminate = m_UI.FindAction("Eliminate", throwIfNotFound: true);
        m_UI_Rotate = m_UI.FindAction("Rotate", throwIfNotFound: true);
        m_UI_Translate = m_UI.FindAction("Translate", throwIfNotFound: true);
        m_UI_Directions = m_UI.FindAction("Directions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Back;
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_Confirm;
    private readonly InputAction m_UI_Space;
    private readonly InputAction m_UI_Mode0;
    private readonly InputAction m_UI_Mode1;
    private readonly InputAction m_UI_Mode2;
    private readonly InputAction m_UI_Mode3;
    private readonly InputAction m_UI_Eliminate;
    private readonly InputAction m_UI_Rotate;
    private readonly InputAction m_UI_Translate;
    private readonly InputAction m_UI_Directions;
    public struct UIActions
    {
        private @PlayerInputs m_Wrapper;
        public UIActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Back => m_Wrapper.m_UI_Back;
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputAction @Confirm => m_Wrapper.m_UI_Confirm;
        public InputAction @Space => m_Wrapper.m_UI_Space;
        public InputAction @Mode0 => m_Wrapper.m_UI_Mode0;
        public InputAction @Mode1 => m_Wrapper.m_UI_Mode1;
        public InputAction @Mode2 => m_Wrapper.m_UI_Mode2;
        public InputAction @Mode3 => m_Wrapper.m_UI_Mode3;
        public InputAction @Eliminate => m_Wrapper.m_UI_Eliminate;
        public InputAction @Rotate => m_Wrapper.m_UI_Rotate;
        public InputAction @Translate => m_Wrapper.m_UI_Translate;
        public InputAction @Directions => m_Wrapper.m_UI_Directions;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Back.started -= m_Wrapper.m_UIActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnBack;
                @Pause.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Confirm.started -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Space.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @Space.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @Space.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @Mode0.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMode0;
                @Mode0.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMode0;
                @Mode0.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMode0;
                @Mode1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMode1;
                @Mode1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMode1;
                @Mode1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMode1;
                @Mode2.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMode2;
                @Mode2.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMode2;
                @Mode2.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMode2;
                @Mode3.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMode3;
                @Mode3.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMode3;
                @Mode3.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMode3;
                @Eliminate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnEliminate;
                @Eliminate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnEliminate;
                @Eliminate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnEliminate;
                @Rotate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRotate;
                @Translate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTranslate;
                @Translate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTranslate;
                @Translate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTranslate;
                @Directions.started -= m_Wrapper.m_UIActionsCallbackInterface.OnDirections;
                @Directions.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnDirections;
                @Directions.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnDirections;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
                @Mode0.started += instance.OnMode0;
                @Mode0.performed += instance.OnMode0;
                @Mode0.canceled += instance.OnMode0;
                @Mode1.started += instance.OnMode1;
                @Mode1.performed += instance.OnMode1;
                @Mode1.canceled += instance.OnMode1;
                @Mode2.started += instance.OnMode2;
                @Mode2.performed += instance.OnMode2;
                @Mode2.canceled += instance.OnMode2;
                @Mode3.started += instance.OnMode3;
                @Mode3.performed += instance.OnMode3;
                @Mode3.canceled += instance.OnMode3;
                @Eliminate.started += instance.OnEliminate;
                @Eliminate.performed += instance.OnEliminate;
                @Eliminate.canceled += instance.OnEliminate;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Translate.started += instance.OnTranslate;
                @Translate.performed += instance.OnTranslate;
                @Translate.canceled += instance.OnTranslate;
                @Directions.started += instance.OnDirections;
                @Directions.performed += instance.OnDirections;
                @Directions.canceled += instance.OnDirections;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IUIActions
    {
        void OnBack(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnMode0(InputAction.CallbackContext context);
        void OnMode1(InputAction.CallbackContext context);
        void OnMode2(InputAction.CallbackContext context);
        void OnMode3(InputAction.CallbackContext context);
        void OnEliminate(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnTranslate(InputAction.CallbackContext context);
        void OnDirections(InputAction.CallbackContext context);
    }
}
